### ISSUE TITLE
Support standard HTML etag headers for Atlas REST APIs

### ISSUE THREAD

**Issue by phaumer** [zowe/explorer-server#10]
Instead of providing the checksum in the body, make it part of the REST protocol using ETag and If-None-Match headers.  

[https://en.wikipedia.org/wiki/HTTP_ETag]

This is important as the current PUT operation also does not return the new checksum, hence a client always needs to run another GET, which is very performance intensive for very large files.  It would also be good to have a HEAD operation that would only return the ETAG header as well for performance reasons.

**Comment by phaumer** [comment]
@Joe-Winchester @Colin-Stone can this item be made a priority as it has a performance impact?

**Comment by Colin-Stone** [comment]
A number of the API's are being rewritten prior to GA and @stevenhorsman is aware of this request.

**Comment by stevenhorsman** [comment]
E-Tag and If-Match have been added in the new data-set apis
