### ISSUE TITLE
USS get content API overwrites file contents

### ISSUE THREAD

**Issue by jordanCain** [zowe/explorer-server#15]
When sending a GET USS content request with the explorer-server the response is 204, no content. The file contents of the file are overwritten in the process with the content `{“request”:“chtag”,“action”:“list”}` 

When getting the attributes of the file he response is as expected. All MVS and JES APIs seem to be functioning as expected.

The issue has been observed both using the api explorer and using curl. curl request: `curl --user <username>:<password> -k -X GET --header 'Accept: application/json' "https://<z/os host name>:7443/Atlas/api/uss/files/path/to/file"`

This bug has only been observed by one user thus far.

**Comment by jordanCain** [comment]
This issue was found to be a result of the zosmf API overwriting file contents with the chtag action json object we send when checking for codepages. 

Further investigation is required to determine why this has only been seen on one system

**Comment by stevenhorsman** [comment]
We no longer have a USS server, but need to consider this if we recreate one in future
