### ISSUE TITLE
Inconsistent responses in GET jobs vs GET job steps 

### ISSUE THREAD

**Issue by jordanCain** [zowe/explorer-server#16]
The GET jobs/{jobName}/ids/{jobId}/steps endpoint returns a 404 response code no job steps found message when there are no job steps.

When GET jobs/{jobName}/ids/ is called and no jobs are found a 200 response code and empty array is returned.

We should consider bringing the response inline to be consistent

**Comment by stevenhorsman** [comment]
Fixed as part of tomcat re-write:
http --verify=no -a stevenh:**** GET https://localhost:8443/api/v1/jobs/TESTJOBX/JOB26797/steps
HTTP/1.1 200
