### ISSUE TITLE
Job names used in Zowe address space should be unique and meaningful

### ISSUE THREAD

**Issue by alvin-tan** [zowe/explorer-server#20]
Feedback from Glenn Crawford

The way it current runs, it creates 11 address spaces with 5 pairs of duplicate names: 

JOBNAME  StepName ProcStep JobID   
ZOWESVR6 *OMVSEX           STC07486
ZOWESVR6 STEP1             STC07485
ZOWESVR7 STEP1             STC07487
ZOWESVR7 *OMVSEX           STC07488
ZOWESVR9 *OMVSEX           STC07489
ZOWESVR1 *OMVSEX           STC07490
ZOWESVR3 STEP1             STC07492
ZOWESVR1 STEP1             STC07493
ZOWESVR3 *OMVSEX           STC07494
ZOWESVR9 STEP1             STC07503
ZOWESVR  ZOWESVR  ZOWESTEP STC07539
 
This creates a few issues.  

It isn't obvious what is running in each of these address spaces. 
Since the only address space that can be displayed is ZOWESVR, the others can't be displayed to see what is running in them. 
Duplicate job names generate duplicate RMF entries, which creates problems for our tools that extract the RMF data. 
Since the extract tools can't distinguish between the two duplicate entries, only one set of data is extracted.   
This may lead to some confusion when collecting customer data for performance problems. 

I would highly recommend the names be changed to unique and more meaningful job names.  
Maybe something like ZOWESxx1 for the *OMVSEX job and ZOWESxx2 for the corresponding STEP1 job.

**Comment by stevenhorsman** [comment]
This is not an issues with explorer-server. Please re-create in a more appropriate repo, like zowe-install-packaging
