### ISSUE TITLE
Runaway CPU by ZOWESVR3

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/explorer-server#21]
Customers are reporting that ZOWESVR is using a lot of CPU even when idling.

**Comment by Joe-Winchester** [comment]
It looks as though ZOWESVR3 is the task responsible for using a lot of CPU even when idling.  We're working on a long term fix, but in the interim we are looking for ways to see if configuration settings can be changed to help the issue.

For anyone experiencing runaway idle CPU to confirm that it's same problem we're tracking here
1) Start up ZOWE excluding the Java Liberty explorer-server.
To do this navigate into the /scripts/internal folder in an installed Zowe runtime, e.g.
/MV3B/zmp/zowe/zowe_0.9.1/scripts/internal  
the file 
run-zowe.sh contains the script that brings up the five servers that run as part of Zowe.  If you cat the file to look at its contents the last five lines are:
 
`dirname $0`/../../zlux-example-server/bin/nodeServer.sh --allowInvalidTLSProxy=true &
`dirname $0`/../../api-mediation/scripts/api-mediation-start-discovery.sh
`dirname $0`/../../api-mediation/scripts/api-mediation-start-catalog.sh
`dirname $0`/../../api-mediation/scripts/api-mediation-start-gateway.sh
`dirname $0`/../../explorer-server/wlp/lib/native/zos/s390x/bbgzsrv Atlas

 The first line brings up the node server for the virtual desktop.
The next three lines bring up the tomcat servers for the API mediation layer (discovery server, API catalog, API gateway).  
The last line brings up the Atlas (aka explorer-server) that is used for the MVS, USS and JES Explorer.
 
Comment out the line that ends ...bbgzsrv Atlas by putting a # symbol as the first character in the line.
Restart Zowe (stop using /scripts/zowe-stop.sh in USS or else /C ZOWESVR in SDSF.  Start using /scripts/zowe-start/sh in USS or else /S ZOWESVR in SDSF).
This will bring up the four remaining Zowe servers but not the Liberty one.  Look at CPU to confirm that removing Liberty removed the excessive CPU with node and 3 * Tomcat remaining.

2) If removing Liberty proves useful
 
We need to find what in Liberty is burning the CPU.  It is possible that Liberty is polling frequently in idle time for any updates, and to test whether that's the case navigate to 
 
/tmp/zowe/zowe_0.9.1/explorer-server/wlp/usr/servers/Atlas/server.xml
 
and add the following two lines as XML tags

```<config updateTrigger="disabled"/>```
```<applicationMonitor updateTrigger="disabled" dropinsEnabled="false"/>```
 
Comment back in the run-zowe.sh line to start the Atlas server, bounce the ZOWESVR so it brings up all five servers, leave to idle and see if this has a reduction in CPU idle consumption.

**Comment by armstrongibm** [comment]
@Joe-Winchester thanks! I am getting this exact issue.

When I remove Atlas, the runaway cpu disappears.

When I add it back in, plus the removal of the polling updates config helps, but ZOWESVR3 continues to nibble around 3% CPU at all times despite no users using Zowe.

**Comment by Joe-Winchester** [comment]
Long term by 1.0 we are removing the Atlas Liberty server and replacing it with a Tomcat server.  It's good that server.xml dropped the CPU to be a 3% nibble - what was it beforehand ?

**Comment by armstrongibm** [comment]
It was ~30-60%! A very good step in the right direction. Is tomcat generally more lightweight than liberty? What's the strategic decision behind that move?

**Comment by armstrongibm** [comment]
There is an io spike every second, which pushes cpu xycles and also io operations, which represents the remaining 3% nibble, which still suggests something polling on the Atlas side, i'll investigate.

**Comment by Joe-Winchester** [comment]
@armstrongibm - the overriding move from Liberty to Tomcat is to try and get a stack of software in Zowe was able to be shipped under the open source EPL 2.0 license.  Liberty is a great piece of software but isn't' able to be delivered under EPL 2.0.  Tomcat is already used by Zowe for its API gateway, its API catalog and its API discovery layer, so consolidating on Tomcat having a fourth Tomcat microservice made sense for the software stack.

**Comment by armstrongibm** [comment]
Makes a lot of sense :) - thanks @Joe-Winchester

**Comment by Joe-Winchester** [comment]
This is fixed in 0.9.4
