### ISSUE TITLE
Query for the DD statements fails if the JCL is closed with // (job end)

### ISSUE THREAD

**Issue by jordanCain** [zowe/explorer-server#26]
If a JCL is ended with //, such as:

//INGJREXX PROC
//********************************************************************
//* *
//* ZOWE DEMO JCL *
//* *
//********************************************************************
//STEP1 EXEC PGM=IKJEFT01,TIME=1440,REGION=5M,
// PARM=‘HELLOW’
//SYSPROC DD DISP=SHR,DSN=PP.ING.SA.CLIST
//SYSTSPRT DD SYSOUT=*
//SYSTSIN DD DUMMY
//

query of https://HOSTNAME:PORT/api/v1/jobs/JOBNAME/ids/JOBINSTANCENAME/steps/STEPNUM/dds will fail with status code 500, error message is: java.lang.StringIndexOutOfBoundsException

Originally raised by @CindyZX 
related: https://github.com/zowe/explorer-jes/issues/27

**Comment by stevenhorsman** [comment]
dds is no longer an offered end point
