### ISSUE TITLE
Hardcode or provide option to set z/OSMF call timeout

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/explorer-server#27]
Based on z/OSMF document, it accepts `X-IBM-Response-Timeout` header when making API request. But maximum timeout is `600` seconds.

We can hardcode the 600 timeout to all internal z/OSMF call, or we provide a way to let the API consumer to set timeout for each call.

**Comment by stevenhorsman** [comment]
I've hard coded the zosmf endpoint timeout to be 600. If we want to customise this we can raise a issue against explorer-api-common
