### ISSUE TITLE
Implement whitelist for X-Frame-Options

### ISSUE THREAD

**Issue by jordanCain** [zowe/explorer-server#28]
We should whitelist the allowed embedders of any web application surfaced via the explorer server.

The X-Frame-Options header can be used to achieve this, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by stevenhorsman** [comment]
@jordanCain - this is assigned to the explorer-server repo, but it looks like a UI piece of work to me? Is there anything you need doing on the SpringBoot apps for this?

**Comment by jordanCain** [comment]
@stevenhorsman Now we've switched over to the UIs being served from Node it'll have to go into the Node server config. I'll create a new issue for this in the https://github.com/zowe/explorer-ui-server repo
