### ISSUE TITLE
Second frame of job spool  websocket always returns job no longer active

### ISSUE THREAD

**Issue by jordanCain** [zowe/explorer-server#4]
The first frame of the websocket is successfully delivered but no other frames are received, the socket just gets closed. 

Below shows the close message from the socket.

![screen shot 2018-09-13 at 11 36 42](https://user-images.githubusercontent.com/30590180/45483609-54eb4300-b749-11e8-8eef-7f72678f769e.png)

**Comment by stevenhorsman** [comment]
The websocket APIs have been removed from 1.0
